# Generated by Django 2.1.10 on 2019-08-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190802_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='skype',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='1', max_length=10),
        ),
    ]
