# Generated by Django 2.1.10 on 2019-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190808_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_type',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
