# Generated by Django 2.1.10 on 2019-08-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190808_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='capping_period_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
