# Generated by Django 2.1.10 on 2019-08-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190809_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
