# Generated by Django 2.1.10 on 2019-08-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190809_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='tracking_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
