# Generated by Django 2.1.10 on 2019-08-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20190809_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='capping_amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
