# Generated by Django 2.1.10 on 2019-08-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20190809_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='storagetype',
            field=models.CharField(choices=[('sql', 'sql'), ('web', 'web'), ('url', 'url'), ('html', 'html'), ('html5', 'html5')], default='sql', max_length=10),
        ),
        migrations.AddField(
            model_name='banners',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
