# Generated by Django 2.1.10 on 2019-08-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20190813_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_vast_element',
            name='autoplay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='creative_view',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='end_pixel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='impression_pixel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='mid_pixel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='mute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='quater_pixel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='skip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='skip_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='start_pixel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='third_party_click',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='third_quater_pixel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_companion_banner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_overlay_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_overlay_text_call',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_overlay_text_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_overlay_text_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_overlay_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_thirdparty_erorr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_thirdparty_impression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_video_clickthrough_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_video_delivery',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_video_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_video_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_video_outgoing_filename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_video_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_video_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
