# Generated by Django 2.1.10 on 2019-09-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20190823_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rv_ad_zone_assoc',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rv_ad_zone_assoc',
            name='link_type',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rv_ad_zone_assoc',
            name='priority',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='rv_ad_zone_assoc',
            name='priority_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='rv_ad_zone_assoc',
            name='to_be_delivered',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
