# Generated by Django 2.1.10 on 2019-09-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20190903_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='change_passwordStatus',
            field=models.IntegerField(default=0),
        ),
    ]
