# Generated by Django 2.1.10 on 2019-09-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_users_change_passwordstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
