# Generated by Django 2.1.10 on 2019-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_users_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher_access',
            fields=[
                ('associd', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(default=0)),
                ('clientid', models.IntegerField(default=0)),
            ],
        ),
    ]
