# Generated by Django 2.1.10 on 2019-09-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_publisher_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher_access',
            old_name='clientid',
            new_name='affiliateid',
        ),
    ]
