# Generated by Django 2.1.10 on 2019-09-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20190910_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_assoc',
            fields=[
                ('associd', models.AutoField(primary_key=True, serialize=False)),
                ('child_id', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
    ]
