# Generated by Django 2.1.10 on 2019-09-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20190916_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='reportinterval',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
    ]
