# Generated by Django 2.1.10 on 2019-09-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20190916_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
