# Generated by Django 2.1.10 on 2019-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20190916_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_element_type',
            field=models.CharField(default='', max_length=16, null=True),
        ),
    ]
