# Generated by Django 2.1.10 on 2019-09-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20190920_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_vast_element',
            name='vast_video_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
