# Generated by Django 2.1.10 on 2019-10-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20191030_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='ad_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='conversions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='impressions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='requests',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='total_basket_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
