# Generated by Django 2.1.10 on 2019-10-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20191031_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='conversions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='requests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
