# Generated by Django 2.1.10 on 2019-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20191031_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
