# Generated by Django 2.1.10 on 2019-10-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20191031_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='ad_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='creative_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rv_data_summary_ad_hourly',
            name='requests',
            field=models.IntegerField(default=0),
        ),
    ]
